<h1 align="center"> IST 5520 Milestone 1: Proposal </h1>
<h3 align="center"> AirBnB Dataset </h3>

<h4 align="left"> Student: Ronald Adomako </h3>
<h4 align="left"> Student: Idris Dobbs </h3>
<h4 align="left"> Student: Nikhil Srirama Sai </h3>
<h4 align="left"> Student: Narendra Chigili </h3>

# Instruction 1: discussion and dataset

1. Discuss with your group members. Choose one of the datasets provided by the
instructor for your group project.

#### We chose the AirBnB dataset for New York City (NYC). We want to build a model that indicates whether hosts are charging an optimum amount for their rental.

http://insideairbnb.com/new-york-city/

https://docs.google.com/spreadsheets/d/1iWCNJcSutYqpULSQHlNyGInUvHg2BoUGoNRIGa6Szc4/edit?usp=sharing

http://insideairbnb.com/get-the-data

http://data.insideairbnb.com/united-states/ny/new-york-city/2022-09-07/visualisations/listings.csv

# Instruction 2: Articles

Review at least three articles (peer-reviewed journal or conference articles) that are
relevant to your selected dataset. Identify an interesting business problem that can be
solved by using business analytics methods. Submit your project proposal.

### [Airbnb and House Prices in Amsterdam â€“ part-2](https://medium.com/mobgen/airbnb-and-house-prices-in-amsterdam-part-2-b0fd12db4ed2)

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [39]:
csv_URL = "http://data.insideairbnb.com/united-states/ny/new-york-city/2022-09-07/visualisations/listings.csv"
df2 = pd.read_csv(csv_URL)
df2

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,77765,Superior @ Box House,417504,The Box House Hotel,Brooklyn,Greenpoint,40.737770,-73.953660,Hotel room,308,2,42,2022-07-18,0.30,30,217,4,NaN
1,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.645290,-73.972380,Private room,299,30,9,2018-10-19,0.11,9,356,0,NaN
2,45910,Beautiful Queens Brownstone! - 5BR,204539,Mark,Queens,Ridgewood,40.703090,-73.899630,Entire home/apt,425,30,13,2019-11-12,0.10,6,365,0,NaN
3,45935,Room in Beautiful Townhouse.,204586,L,Bronx,Mott Haven,40.806350,-73.922010,Private room,60,30,0,NaN,NaN,1,83,0,NaN
4,45936,Couldn't Be Closer To Columbia Uni,867225,Rahul,Manhattan,Morningside Heights,40.806300,-73.959850,Private room,75,31,135,2022-07-11,0.95,1,219,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39876,27577588,Luxury Studio ON Grove Street E0C - B1CA,37412692,Kim,Manhattan,Ellis Island,40.718220,-74.037940,Entire home/apt,135,365,2,2019-09-16,0.04,7,365,0,NaN
39877,654151117629853651,Lovely 3- bedroom apartment,117540494,Miriam,Queens,Rosedale,40.647244,-73.720088,Entire home/apt,180,1,5,2022-08-24,1.92,1,0,5,NaN
39878,553754115911961053,Trendy 3-bedroom apartment near Manhattan,15048320,India,Manhattan,Upper West Side,40.787320,-74.004470,Entire home/apt,240,5,18,2022-08-22,2.87,1,152,18,NaN
39879,698195550745703156,"Luxurious private waterfront terrace, 2BR 2BA Apt",151487807,Asser,Brooklyn,Williamsburg,40.709192,-73.970121,Entire home/apt,400,30,0,NaN,NaN,1,311,0,NaN
39880,48971505,Just Blocks to Grove PATH and JC Med Ctr,46201,J,Manhattan,Ellis Island,40.718350,-74.044160,Private room,40,1,15,2021-10-25,0.91,1,0,4,NaN

In [2]:
#csv_URL = "http://data.insideairbnb.com/united-states/ny/new-york-city/2022-09-07/visualisations/listings.csv"
df = pd.read_csv('./listings.csv')
df

/opt/anaconda3/envs/MyEnv/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (68) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20220907064715,2022-09-07,city scrape,Clean & quiet apt home by the park,Renovated apt home in elevator building.<br />...,Close to Prospect Park and Historic Ditmas Park,https://a0.muscache.com/pictures/3949d073-a02e...,2787,...,5.00,4.75,4.88,NaN,f,9,1,6,2,0.11
1,2595,https://www.airbnb.com/rooms/2595,20220907064715,2022-09-07,city scrape,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/f0813a11-40b2...,2845,...,4.80,4.81,4.40,NaN,f,3,3,0,0,0.31
2,5121,https://www.airbnb.com/rooms/5121,20220907064715,2022-09-07,city scrape,BlissArtsSpace!,One room available for rent in a 2 bedroom apt...,NaN,https://a0.muscache.com/pictures/2090980c-b68e...,7356,...,4.91,4.47,4.52,NaN,f,2,0,2,0,0.31
3,45910,https://www.airbnb.com/rooms/45910,20220907064715,2022-09-07,city scrape,Beautiful Queens Brownstone! - 5BR,"<b>The space</b><br />Beautiful, fully furnish...",NaN,https://a0.muscache.com/pictures/27117627/19ff...,204539,...,5.00,4.82,4.55,NaN,f,6,6,0,0,0.10
4,5136,https://www.airbnb.com/rooms/5136,20220907064715,2022-09-07,city scrape,"Spacious Brooklyn Duplex, Patio + Garden",We welcome you to stay in our lovely 2 br dupl...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,7378,...,5.00,4.67,5.00,NaN,f,1,1,0,0,0.03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39876,43728504,https://www.airbnb.com/rooms/43728504,20220907064715,2022-09-08,previous scrape,Private Modern House by The Beach,Private modern house by the Beach with all com...,Rockaway Beach is a neighborhood that gives it...,https://a0.muscache.com/pictures/6c950656-b090...,23049030,...,5.00,4.94,4.88,NaN,f,1,1,0,0,1.22
39877,44578886,https://www.airbnb.com/rooms/44578886,20220907064715,2022-09-08,previous scrape,Beautiful apartment - minutes to NYC,Our apartment is straight across the river fro...,Our apartment is located in a very interesting...,https://a0.muscache.com/pictures/dd5163c1-7e02...,48009648,...,4.96,4.81,4.85,NaN,f,1,1,0,0,2.12
39878,46355090,https://www.airbnb.com/rooms/46355090,20220907064715,2022-09-08,previous scrape,"1 Bedroom Basement, NEWLY Renovated",With easy access to multiple bus stops and the...,NaN,https://a0.muscache.com/pictures/64c81ee7-b396...,371552251,...,4.36,4.36,4.55,NaN,t,1,1,0,0,0.50
39879,698195550745703156,https://www.airbnb.com/rooms/698195550745703156,20220907064715,2022-09-08,city scrape,"Luxurious private waterfront terrace, 2BR 2BA Apt","This two bed, two bath apartment overlooking t...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,151487807,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
39880,48971505,https://www.airbnb.com/rooms/48971505,20220907064715,2022-09-08,previous scrape,Just Blocks to Grove PATH and JC Med Ctr,Very convenient to the Grove St PATH (5 min wa...,NaN,https://a0.muscache.com/pictures/b12bc7dc-573c...,46201,...,4.73,4.87,4.47,NaN,f,1,0,1,0,0.91

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39881 entries, 0 to 39880
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            39881 non-null  int64
 1   listing_url                                   39881 non-null  object
 2   scrape_id                                     39881 non-null  int64
 3   last_scraped                                  39881 non-null  object
 4   source                                        39881 non-null  object
 5   name                                          39868 non-null  object
 6   description                                   39036 non-null  object
 7   neighborhood_overview                         23466 non-null  object
 8   picture_url                                   39881 non-null  object
 9   host_id                                       39881 non-null  int64
 10  host_url                                      39881 non-null  object
 11  host_name                                     39831 non-null  object
 12  host_since                                    39831 non-null  object
 13  host_location                                 32998 non-null  object
 14  host_about                                    22509 non-null  object
 15  host_response_time                            26333 non-null  object
 16  host_response_rate                            26333 non-null  object
 17  host_acceptance_rate                          28020 non-null  object
 18  host_is_superhost                             39852 non-null  object
 19  host_thumbnail_url                            39831 non-null  object
 20  host_picture_url                              39831 non-null  object
 21  host_neighbourhood                            31650 non-null  object
 22  host_listings_count                           39831 non-null  float64
 23  host_total_listings_count                     39831 non-null  float64
 24  host_verifications                            39881 non-null  object
 25  host_has_profile_pic                          39831 non-null  object
 26  host_identity_verified                        39831 non-null  object
 27  neighbourhood                                 23467 non-null  object
 28  neighbourhood_cleansed                        39881 non-null  object
 29  neighbourhood_group_cleansed                  39881 non-null  object
 30  latitude                                      39881 non-null  float64
 31  longitude                                     39881 non-null  float64
 32  property_type                                 39881 non-null  object
 33  room_type                                     39881 non-null  object
 34  accommodates                                  39881 non-null  int64
 35  bathrooms                                     0 non-null      float64
 36  bathrooms_text                                39797 non-null  object
 37  bedrooms                                      36098 non-null  float64
 38  beds                                          38997 non-null  float64
 39  amenities                                     39881 non-null  object
 40  price                                         39881 non-null  object
 41  minimum_nights                                39881 non-null  int64
 42  maximum_nights                                39881 non-null  int64
 43  minimum_minimum_nights                        39867 non-null  float64
 44  maximum_minimum_nights                        39867 non-null  float64
 45  minimum_maximum_nights                        39867 non-null  float64
 46  maximum_maximum_nights                        39867 non-null  float64
 47  minimum_nights_avg_ntm                        39867 non-null  float64
 48  maximum_nights_avg_ntm                        39867 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              39881 non-null  object
 51  availability_30                               39881 non-null  int64
 52  availability_60                               39881 non-null  int64
 53  availability_90                               39881 non-null  int64
 54  availability_365                              39881 non-null  int64
 55  calendar_last_scraped                         39881 non-null  object
 56  number_of_reviews                             39881 non-null  int64
 57  number_of_reviews_ltm                         39881 non-null  int64
 58  number_of_reviews_l30d                        39881 non-null  int64
 59  first_review                                  31519 non-null  object
 60  last_review                                   31519 non-null  object
 61  review_scores_rating                          31519 non-null  float64
 62  review_scores_accuracy                        31056 non-null  float64
 63  review_scores_cleanliness                     31066 non-null  float64
 64  review_scores_checkin                         31052 non-null  float64
 65  review_scores_communication                   31061 non-null  float64
 66  review_scores_location                        31049 non-null  float64
 67  review_scores_value                           31049 non-null  float64
 68  license                                       5 non-null      object
 69  instant_bookable                              39881 non-null  object
 70  calculated_host_listings_count                39881 non-null  int64
 71  calculated_host_listings_count_entire_homes   39881 non-null  int64
 72  calculated_host_listings_count_private_rooms  39881 non-null  int64
 73  calculated_host_listings_count_shared_rooms   39881 non-null  int64
 74  reviews_per_month                             31519 non-null  float64
dtypes: float64(22), int64(17), object(36)
memory usage: 22.8+ MB

In [4]:
df['host_location']

0           New York, NY
1           New York, NY
2           New York, NY
3           New York, NY
4           New York, NY
              ...
39876       New York, NY
39877       New York, NY
39878    Floral Park, NY
39879       New York, NY
39880    Jersey City, NJ
Name: host_location, Length: 39881, dtype: object

In [34]:
import geopy
from geopy.geocoders import Nominatim

#GeoLocator = Nominatim()
# nom = Nominatim(user_agent="http")
geopy.geocoders.options.default_user_agent = "my-application"
#Nominatim(user_agent="my-application")
ip = open('mac.txt', "r")

In [35]:
macAdr = ip.readlines()[0]

In [36]:
geolocator = geopy.Nominatim(user_agent=macAdr)
# geolocator = geopy.Nominatim(user_agent='my-application')
#geolocator = geopy.geocoders.options.default_user_agent = "my-application"

def get_zipcode(df, geolocator, lat_field, lon_field):
    location = geolocator.reverse((df[lat_field], df[lon_field]))
    return location.raw['address']['postcode']


df = pd.DataFrame({
    'Lat': [29.39291, 29.39923, 29.40147, 29.38752, 29.39291, 29.39537, 29.39343, 29.39291, 29.39556],
    'Lon': [-98.50925, -98.51256, -98.51123, -98.52372, -98.50925, -98.50402, -98.49707, -98.50925, -98.53148]
})
zipcodes = df.apply(get_zipcode, axis=1, geolocator=geolocator, lat_field='Lat', lon_field='Lon')

In [37]:
zipcodes

0    78204
1    78204
2    78204
3    78225
4    78204
5    78204
6    78204
7    78204
8    78225
dtype: object